Repository WebAhead/wajjbat-frontend, pull requests merged in 2020-03, with the labels that each got.

#31 Maps asset development, squash a couple of auth UI bugs
  package-lock.json
  src/components/BusinessesMap/index.jsx
  src/components/ChooseLocation/index.jsx
  src/components/GoogleMaps/index.jsx
  src/components/NavBar/index.jsx
  src/components/NavBar/style.scss
  src/pages/Home/components/PopupMarker/index.jsx
  src/pages/Home/components/PopupMarker/style.scss
  src/pages/Home/index.jsx
Labels: merge-conflicts

#47 Filter by radius
  package.json
  src/components/BusinessesMap/index.jsx
  src/components/Filtering/index.jsx
  src/components/Filtering/style.scss
  src/components/Footer/index.jsx
  src/pages/BusinessPage/components/BusinessPageImageGallery/index.jsx
  src/pages/BusinessPage/components/BusinessReviews/index.jsx
  src/pages/BusinessPage/index.jsx
  src/pages/Home/index.jsx
Labels: awaiting-review, discuss, enhancement, priority-4

#46 Adds search by name, type, cuisine
  src/Languages/ar.js
  src/Languages/en.js
  src/components/BusinessesMap/index.jsx
  src/components/SearchBar/index.jsx
  src/components/SearchBar/style.scss
  src/pages/Home/index.jsx
Labels: enhancement
